nopal/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from management.views import cambiarContra

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('administracion/', include('management.urls')),
    path('facturacion/', include('invoice.urls')),
    
    #  # Logueo
    path('admin-login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='admin-login'),
    path('admin-logout/', auth_views.LogoutView.as_view(), name='admin-logout'),
    
    #recuperacion
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='login/password-email.html',email_template_name='login/password_reset_email.html'),
         name='password-reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='login/new-password.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login/account-recovery.html'), name='password_reset_complete'),
    path('reset/password_change/', auth_views.PasswordChangeView.as_view(template_name='login/login-wifi.html'),name='password_change'),
    # path('cambioC', cambiarContra, name="password_change"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/models.py
from asyncio.windows_events import NULL
from enum import unique
import os
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=u"Nombre", blank=False, db_column="Nombre")
    status = models.BooleanField(default=True, db_column="Status")
    def __str__(self) -> str:
        return ' %s' %(self.name)
    def clean(self):
        self.name = self.name.title()
    class Meta:
        verbose_name = "Categoría"
        verbose_name_plural = "Categorías"
        
class Subcategory(models.Model):
    name = models.CharField(max_length=50,  unique=True, verbose_name=u"Nombre", blank=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name=u"Categoría")
    image = models.ImageField(upload_to='subcategory', null=True, verbose_name=u"Imagen", default='subcategory/Logo.png')
    status = models.BooleanField(default=True)
    def __str__(self) -> str:
        return ' %s' %(self.name)
    def clean(self):
        self.name = self.name.title()
    class Meta:
        verbose_name = "Subcategoría"
        verbose_name_plural = "Subcategorías"

class Brand(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"Nombre", blank=False, db_column="Nombre")
    status = models.BooleanField(default=True)
    def __str__(self) -> str:
        return (self.name)
    def clean(self):
        self.name = self.name.title()
    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"

class Unit(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=u"Unidad de medida", blank=False)
    class Type(models.TextChoices):
        MASA = 'Masa',_('Masa')
        VOLUMEN = 'Volumen',_('Volumen')
    type = models.CharField(max_length=30, choices=Type.choices, default=Type.MASA, verbose_name="Tipo de medida")
    status = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return (self.name)
    def clean(self):
        self.name = self.name.title()
    class Meta:
        verbose_name = "Unidad de Medida"
        verbose_name_plural = "Unidades de Medida"


class Product(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=u"Nombre", blank=False)
    price = models.IntegerField(validators=[MinValueValidator(1)], blank=False, verbose_name=u"Precio")
    description = models.TextField(max_length=150, blank=True, verbose_name=u"Descripción")
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, null=True, verbose_name=u"Subcategoría")
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, verbose_name=u"Marca")
    unitMeasurement = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True, verbose_name=u"Unidad de Medida")
    stock = models.PositiveIntegerField(validators=[MinValueValidator(1)], blank=False, null=True, verbose_name=u"Stock", default=0)
    type = models.CharField(max_length=30, verbose_name="Tipo de medida", null=True , blank=True )
    name_unitMeasurement= models.CharField(max_length=30, blank=True, null=True)
    image = models.ImageField(upload_to='product', null=True, verbose_name=u"Imagen", default='product/Logo.png')
    status = models.BooleanField(default=True)
    def __str__(self) -> str:
        return ' %s' %(self.name)
    def clean(self):
        self.name = self.name.title()
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
    
class Provider(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"Nombre", blank=False)
    phone = models.CharField(max_length=10, verbose_name=u"Teléfono", blank=True)
    email = models.EmailField(max_length=254, verbose_name=u"Correo Electrónico", unique=True)
    status = models.BooleanField(default=True)
    def __str__(self) -> str:
        return (self.name)
    def clean(self):
        self.name = self.name.title()
    class Meta:
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.sql']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Archivo no válido')

class Backup(models.Model):
    name = models.CharField(max_length = 200,default="Copia de Seguridad", blank=True,  verbose_name="Nombre") 
    file = models.FileField(upload_to="media",validators=[validate_file_extension],  verbose_name="Archivo")
    date = models.DateTimeField(auto_now = True)

nopal/templates/modals/ejemplo.html
{% load crispy_forms_tags %}
{% load static %}

<div class="modal fade show" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Nueva Subcategoría</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="div_id_name" class="mb-3">
                        <label for="id_name" class="form-label requiredField">Nombre
                            <span class="asteriskField">*</span>
                        </label>
                        <input type="text" name="name" class="form-control textinput textInput" maxlength="50" required id="id_name">
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>

                <input type="hidden" id="modal-status" value="Agregar">
                <button class="btn_agregar d-block m-auto text-center text-decoration-none py-1 rounded border border-none"
                style="width: 120px;" >Agregar</button>
                </form>
            </div>
        </div>
    </div>
</div>

nopal/templates/modals/m-category.html
{% load crispy_forms_tags %}
{% load static %}


<div class="modal fade" id="modalCategory" tabindex="-1" aria-labelledby="modalCategoryLabel" aria-hidden="true" role="dialog" style="display: block;">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content" >
            <div class="modal-header">
                <h5 class="modal-title" id="modalCategoryLabel">Nuevo Registro</h5>
                {% comment %} <a class="btn-close" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#modalCategory" href="{% url 'product' %}" aria-label="Close"></a> {% endcomment %}
                <div class="p-0">
                    <button type="button" class="btn btn-outline-success p-0 px-2"  data-bs-dismiss="modal"><img src="{% static 'img/icons/back.svg' %}" alt="Atrás"></button>
                  </div>
            </div>

        <div class="modal-body">
            <form method = 'POST' action= '' enctype = "multipart/form-data" novalidate id = "category-form">
                {% csrf_token %}
                {{form.as_p}}
               
            </form>
            <div class="modal-footer">
                <a class="btn btn-danger Btn-White" data-bs-dismiss="modal" href="{% url 'product' %}">Cancelar</a>
                <input type="submit" class="btn_agregar d-block m-auto text-center text-decoration-none py-1 rounded border border-none" 
                style="width: 120px;" data-bs-toggle="tooltip" data-bs-placement="right" title="Agregar producto" value="Agregar" />
                </form>
            </div>
      </div>
    </div>
</div>
  

nopal/templates/modals/m-help.html
{% load crispy_forms_tags %}
{% load static %}
  <div class="modal fade" id="modalAyuda" tabindex="-1" aria-labelledby="modalAyudaLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content" id="textomodal" >
        <div class="d-flex align-items-center justify-content-between border border-bottom-1 mb-2"style="height: 30px;">
          <h5 style="font-size: auto;" id="modalAyudaLabel">Ayuda</h5>
          <button type="button" class="btn btn-outline-success p-0 px-2"><a href=""><img src="{% static 'img/icons/exit.svg' %}" alt="Cerrar"></a></button>
        </div>
        <div class="modal-body">
          <h3 class="text-center" style="font-size: 22px;">
            <img src="{% static 'img/icons/help.svg' %}" alt="Ayuda">Selecciona una opción en la que necesites ayuda
          </h3>
        </div>
        <div class="py-1 px-4 mb-2">
            <button class="botonOpcionesAyuda d-block align-items-center p-1 m-2 rounded text-decoration-none" style="width: 95%;" data-bs-target="#modalAyudaToggle3" data-bs-toggle="modal" data-bs-dismiss="modal"><img
                  src="{% static 'img/icons/detail.svg' %}" alt="Detalles">Detalles de un producto</button>
            <button class="botonOpcionesAyuda d-block align-items-center p-1 m-2 rounded text-decoration-none"style="width: 95%;" id="opcionesAyuda" data-bs-target="#modalAyudaToggle4" data-bs-toggle="modal" data-bs-dismiss="modal"><img
                  src="{% static 'img/icons/buy.svg' %}" alt="Comprar">Comprar un producto</button>
            <button class="botonOpcionesAyuda d-block align-items-center p-1 m-2 rounded text-decoration-none"style="width: 95%;" id="opcionesAyuda" data-bs-target="#modalAyudaToggle5" data-bs-toggle="modal" data-bs-dismiss="modal"><img
                  src="{% static 'img/icons/shopping-car.svg' %}" alt="Carrito">Mi carrito</button>
            <button class="botonOpcionesAyuda d-block align -items-center p-1 m-2 rounded text-decoration-none"style="width: 95%;" id="opcionesAyuda"><a href="{% static 'document/MANUAL-USUARIO.pdf' %}"><img
                  src="{% static 'img/icons/download.svg' %}" alt="Descargar">Descargar manual</a></button>
          </div>
        </div>
      </div>
    </div>
      
  <div class="modal fade" id="modalAyudaToggle3" tabindex="-1" aria-labelledby="modalAyudaToggleLabel3"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="d-flex align-items-center justify-content-between border border-bottom-1 mb-2"style="height: 30px;">
          <h5 style="font-size: auto;" id="modalAyudaToggleLabel3">Ayuda</h5>
          <div class="p-0">
            <button type="button" class="btn btn-outline-success p-0 px-2" data-bs-target="#modalAyuda" data-bs-toggle="modal" data-bs-dismiss="modal"><img src="{% static 'img/icons/back.svg' %}" alt="Atrás"></button>
            <button type="button" class="btn btn-outline-success p-0 px-2"><a href=""><img src="{% static 'img/icons/exit.svg' %}" alt="Cerrar"></a></button>
          </div>
        </div>
        <div class="modal-body">
          <h3 class="text-center" style="font-size: 22px;">
            <img src="{% static 'img/icons/detail.svg' %}" alt="Detalle">Detalles de un producto
        </div>
        <div class="py-1 px-4 mb-2">
          <p><img src="{% static 'img/icons/point.svg' %}">En la página en la parte superior hay una barra de opciones
            desplegables dónde puede encontrar la categoría del producto que necesite.</p>
          <p><img src="{% static 'img/icons/point.svg' %}">Para buscar un producto en especifico, hay un buscador principal al
            lado del icono de "Iniciar sesión" dónde allí puede escribir el nombre del producto y dar enter.</p>
          <p><img src="{% static 'img/icons/point.svg' %}">En el producto, al dar click en el botón "Agregar" se visualizará
            una ventana emergente sobre el detalle del producto.</p>
          <p><img src="{% static 'img/icons/point.svg' %}">Si quiere comprar el producto, ya visualizando el detalle del
            producto, de click en "Agregar al carrito".</p>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="modalAyudaToggle4" tabindex="-1" aria-labelledby="modalAyudaToggleLabel4" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="d-flex align-items-center justify-content-between border border-bottom-1 mb-2"style="height: 30px;">
          <h5 style="font-size: auto;" id="modalAyudaToggleLabel4">Ayuda</h5>
          <div class="p-0">
            <button type="button" class="btn btn-outline-success p-0 px-2" data-bs-target="#modalAyuda" data-bs-toggle="modal" data-bs-dismiss="modal"><img src="{% static 'img/icons/back.svg' %}" alt="Atrás"></button>
            <button type="button" class="btn btn-outline-success p-0 px-2"><a  href=""><img src="{% static 'img/icons/exit.svg' %}" alt="Cerrar"></a></button>
          </div>
        </div>
        <div class="modal-body">
          <h3 class="text-center" style="font-size: 22px;">
            <img src="{% static 'img/icons/buy.svg' %}" alt="Comprar">Comprar un producto
        </div>
        <div class="py-1 px-4 mb-2">
          <p><img src="{% static 'img/icons/point.svg' %}">Al ingresar a la página, en la parte superior se encuentra
            una barra de opciones dónde puede seleccionar la categoría del producto que quiere comprar.
            Luego de seleccionar la categoría y encontrar su producto, de click al botón "Agregar al
            Carrito".</p>
          <p><img src="{% static 'img/icons/point.svg' %}">A continuación, de click en la parte superior "Tu carrito" y allí
            podrá hacer modificaciones en sus productos.</p>
            <p><img src="{% static 'img/icons/point.svg' %}">Seguido de hacer las modificaciones de click en
              "Siguiente paso" y esto lo dirigirá a Whatsapp donde podrá entablar una conversación con el administrador para 
              concretar su compra.</p>
         
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="modalAyudaToggle5" tabindex="-1" aria-labelledby="modalAyudaToggleLabel5" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="d-flex align-items-center justify-content-between border border-bottom-1 mb-2"style="height: 30px;">
          <h5 style="font-size: auto;" id="modalAyudaToggleLabel5">Ayuda</h5>
          <div class="p-0">
            <button type="button" class="btn btn-outline-success p-0 px-2" data-bs-target="#modalAyuda" data-bs-toggle="modal" data-bs-dismiss="modal"><img src="{% static 'img/icons/back.svg' %}" alt="Atrás"></button>
            <button type="button" class="btn btn-outline-success p-0 px-2"><a  href=""><img src="{% static 'img/icons/exit.svg' %}" alt="Cerrar"></a></button>
          </div>
        </div>
        <div class="modal-body">
          <h3 class="text-center" style="font-size: 22px;">
            <img src="{% static 'img/icons/shopping-car.svg' %}" alt="Carrito">Tu carrito
        </div>
        <div class="py-1 px-4 mb-2">
          <p><img src="{% static 'img/icons/point.svg' %}">De click en el icono "Tu carrito" que aparece en el lado superior
            derecho.</p>
          <p><img src="{% static 'img/icons/point.svg' %}">Seguido de la opción anterior lo dirigirá a la ventana del carrito,
            dónde allí encontrará los productos que ha agregado, pudiendo allí modificar su cantidad.</p>
          <p><img src="{% static 'img/icons/point.svg' %}">En el costado derecho aparece el monto total a pagar, si quiere
            concretar su compra, diríjase a "Siguiente paso".</p>
          <p><img src="{% static 'img/icons/point.svg' %}">Si quiere seguir agregando productos, de click en la opción "Agregar
            productos" y este lo llevará de vuelta a la página para seguir agregando.</p>
        </div>
      </div>
    </div>
  </div>

nopal/templates/modals/m-product.html
{% load static %}
<div class="modal fade " id="modalproduct" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered " style="max-width:700px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Detalle Producto</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class=" col-md-5  p-0">
              <img style="height:300px" class="card-img-top w-100 " src="{{product.image.url}}" alt="">
          </div>
          <div class=" col-md-7   d-flex flex-column align-items-center justify-content-center text-center">
              <div class="row">
                  <h2 class="card-title" >index</h2>
                  <p class="card-text  fw-bold  text-wrap" id="modal_description" >{{product.description}}</p>
                  <div class="row">
                    <div class="col">
                      <strong class="card-text alert alert-warning">Disponibles</strong>
                    </div>
                    <div class="col">
                      <strong class="card-text text-danger" id="modal_stock">{{product.stock}}</strong>
                    </div>
                    <div class="col">
                      <p class="card-text  fw-bold" >Iva: 19%</p>
                    </div>
                  </div>
              </div>
                <strong id="precio_modal"  class=" w-50 border py-1 text-light bg-success mx-auto mt-3">{{product.price|floatformat}} $</strong>
                <a href="#" id="agregar_carrito" class="btn w-75 mx-auto mt-3 text-light" style="background-color: #223016;" >Agregar al carrito</a> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

nopal/templates/modals/m-register.html
{% load crispy_forms_tags %}
{% load static %}


<div class="modal fade show" id="exampleModal" tabindex="-1" aria-labelledby="mainModalLabel" aria-hidden="true" role="dialog" style="display: block;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{modal_title}}</h5>
                <a href="{% url 'registerU' %}"><button class="btn-close"
                    data-bs-dismiss="modal" href="{% url 'registerU' %}" aria-label="Close"></button></a>
            </div>
            <div class="modal-body">
                <p>¿Está seguro de {{modal_txt}} "{{register_id}}"?</p>
                {% if modal == 'editar' %}
                <form action="" method="POST" enctype="multipart/form-data">
                    {{form|crispy}}{% csrf_token %}
                {% elif modal == 'eliminar' %}
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                {% endif %}
            </div>
            <div class="modal-footer">
                <a href="{% url 'registerU' %}" class="btn btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-success">{{modal_submit.title}}</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal-backdrop fade show"></div>

nopal/templates/modals/m-subcategory.html
{% load crispy_forms_tags %}
{% load static %}

{% comment %} <main class="">
    <div>
        <h1 class="text-center">Gestionar {{title_pag}}</h1>
    </div>
</main> {% endcomment %}
<div class="modal fade" id="modalSubcategory" tabindex="-1" aria-labelledby="modalSubcategoryLabel" aria-hidden="true" role="dialog" style="display: block;">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content" >
            <div class="modal-header">
                <h5 class="modal-title" id="modalSubcategoryLabel">Nuevo Registro</h5>
                {% comment %} <a class="btn-close" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#modalCategory" href="{% url 'product' %}" aria-label="Close"></a> {% endcomment %}
                <div class="p-0">
                    <button type="button" class="btn btn-outline-success p-0 px-2"  data-bs-dismiss="modal"><img src="{% static 'img/icons/back.svg' %}" alt="Atrás"></button>
                  </div>
            </div>

        <div class="modal-body">
            <form method='POST' action='' enctype="multipart/form-data" novalidate id="subcategory-form">
                {% csrf_token %}
                <label for="subcategory-name" class="control-label">Nombre</label>
                <span class="asteriskField">*</span>
                {{form.name }}
                <label for="subcategory-category" class="control-label">Categoría</label>
                <span class="asteriskField">*</span>
                {{form.category }}
                <a href="{% url 'm-category' %}" id="add_category" onclick="return showAddPopup(this);"><img
                        src="{% static 'img/icons/plus.svg' %}" data-bs-toggle="tooltip" data-bs-placement="right" title="Agregar categoría"></a>

                <div id="div_id_image" class="mb-3">
                    <label for="subcategory-image" accept="image/*" class="form-label requiredField">Imagen
                    </label>
                    <!-- <input type="file" name="image" class="form-control " accept="image/*" id="id_image">Imagen -->
                    {{form.image }}

                </div>        
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger Btn-White" data-bs-dismiss="modal" href="{% url 'product' %}">Cancelar</a>
                <input type="submit" class="btn_agregar d-block m-auto text-center text-decoration-none py-1 rounded border border-none" 
                style="width: 120px;" data-bs-toggle="tooltip" data-bs-placement="right" title="Agregar producto" value="Agregar" />
                </form>
            </div>
      </div>
    </div>
</div>
  

nopal/templates/modals/modal.html
{% load crispy_forms_tags %}
{% load static %}


<div class="modal fade show" id="exampleModal" tabindex="-1" aria-labelledby="mainModalLabel" aria-hidden="true" role="dialog" style="display: block;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{modal_title}}</h5>
                <a href="{{url_back}}"><button class="btn-close"
                    data-bs-dismiss="modal" href="{{url_back}}" aria-label="Close"></button></a>
            </div>
            <div class="modal-body">
                <p>¿Está seguro de {{modal_txt}} "{{register_id}}"?</p>
                {% if modal == 'editar' or modal == "marcar"%}
                <form action="" method="POST" enctype="multipart/form-data">
                    {{form|crispy}}{% csrf_token %}
                {% elif modal == 'eliminar' or modal == "cerrar" or modal == "desmarcar" %}
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                {% endif %}
            </div>
            <div class="modal-footer">
                <a href="{{url_back}}" class="btn btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-success">{{modal_submit.title}}</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal-backdrop fade show"></div>